### ISSUE TITLE
Status code improve readability

### ISSUE THREAD

**Issue by yuttasartviratpan** [feiwhang/muic_vending_machine#1]
https://github.com/feiwhang/muic_vending_machine/blob/4f7e86a3b5aed3c265b43f4adbd02d5f182071a7/app/main.py#L45-L46

The status code could be defined as a constant to further improve readability.

Ex:
in (new) http_status_code.py
OK = 200
INTERNAL_SERVER_ERROR = 500

in main.py
import http_status_code

status_code=http_status_code.OK
status_code=http_status_code.INTERNAL_SERVER_ERROR

etc

**Comment by feiwhang** [comment]
I use HTTPStatus from http, Thank you!
